spring.application.name=zotroul

spring.datasource.url=jdbc:postgresql://localhost:5432/zotroul
spring.datasource.username=zotroul
spring.datasource.password=zotroul
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.hibernate.ddl-auto=create
